### PR TITLE
Go 1.14; previously a mix 1.11, 1.12 and 1.13

### PR DESCRIPTION
**Pull request by pda**
Use Go 1.14 in CI, and update `go.mod` to match.

### CODE REVIEW

**Comment by lox** [comment]
I figured I'd go for a blended approach, but fine, if you want a bland consistency...

**Comment by pda** [comment]
I was actually hoping for something more interesting blended in there; maybe an old 1.2 vintage from 2013, or perhaps just a splash of a broken prerelease.

**Comment by lox** [comment]
I'm all about vintage software @pda.

**Comment by pda** [comment]
Rebased onto #89 to get some CI coverage.

**Pull request merged**
