### PR TITLE
Remove keyring entirely and use config json

### PR DESCRIPTION
**Pull request by lox**
This removes entirely the fancy keyring integration in favour of a much simpler config file. 

Why? Every time I come back to this tool to iterate on it, a weird native interface library is broken and it won't build. Beyond that, it means this tool needs binary builds (for code-signing) which is awkward and impractical.

This would be a very breaking change! Closes https://github.com/buildkite/cli/issues/114.

### CODE REVIEW

**Comment by dontlaugh** [comment]
I built your branch, and it worked great

**Comment by sj26** [comment]
Thanks @lox. I mostly agree, and err on the side of development productivity.

How painful do you think it is to have tokens in files? Is there another way to do keychain tokens nicely? Every time I explore that space it seems pretty spicy.

This repo also doesn't have a clear caretaker at the moment. I suspect it would be the decision of whoever wants to pick this up and start iterating on it. So this might need to wait for that moment.

**Comment by pda** [comment]
Yeah, seems reasonable.
I think this project needs to be as easy to occasionally-maintain as possible, so this would be a win.

I wonder if there's anything else that should be bundled into a v2.x release, given we'll probably need to bump major version for the breaking change 🤔

I guess we can merge in the mean time, to at least get this on `main`.

**Comment by pda** [comment]
Rebased onto `main` to get https://github.com/buildkite/cli/pull/131 and added a small README tweak.

@moskyb and I have tested it locally, including the whole GraphQL token and GitHub OAuth flow, verifying the keys end up in the config file, and can be used to list pipelines 👌🏼

**Review by pda — APPROVED** [review]

**Comment by pda** [comment]
Hrmm… not sure if this is relevant to this PR, but I thought the removal of keyring would ideally make this not happen when running `bk --help`:

image

**Comment by pda** [comment]
I think this is just macOS these days… it's a downloaded binary, so it “warns” the user.
`xattr -d com.apple.quarantine <filename>` did the trick.

**Pull request merged**
